control:
  hosts:
    ws-mgordillo:
      ansible_connection: local
centos:
  hosts:
    centos1:
    centos2:
    centos3:
debian:
  hosts:
    debian1:
    debian2:
    debian3:
linux:
  children:
    centos:
    ubuntu:
all:
  vars:
    ansible_user: user
    ansible_become: user
    ansible_become_pass: newpass

